#!/usr/bin/env sh
set -eu

cd "$(dirname "$0")"

if ! command -v cargo >/dev/null 2>&1; then
    echo "Rust/Cargo was not found. Install Rust from https://rustup.rs/." >&2
    exit 1
fi

if [ ! -f .env ]; then
    if ! command -v psql >/dev/null 2>&1; then
        echo "PostgreSQL client tools were not found." >&2
        exit 1
    fi
    if ! command -v openssl >/dev/null 2>&1; then
        echo "OpenSSL was not found; it is required to generate local secrets." >&2
        exit 1
    fi
    if ! command -v sudo >/dev/null 2>&1; then
        echo "sudo was not found. Create the adelia_app role and adelia_dev database manually, then copy .env.example to .env." >&2
        exit 1
    fi

    database_password=$(openssl rand -hex 36)
    app_secret=$(openssl rand -hex 48)

    sudo -u postgres psql -v ON_ERROR_STOP=1 --set=database_password="$database_password" <<'SQL'
SELECT format('CREATE ROLE adelia_app LOGIN PASSWORD %L', :'database_password')
WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'adelia_app') \gexec
ALTER ROLE adelia_app PASSWORD :'database_password';
SELECT 'CREATE DATABASE adelia_dev OWNER adelia_app'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'adelia_dev') \gexec
SQL

    umask 077
    cat > .env <<EOF
# Generated by dev.sh for loopback-only development.
DATABASE_URL=postgres://adelia_app:$database_password@localhost:5432/adelia_dev
APP_SECRET=$app_secret
BIND_ADDR=127.0.0.1:8080
PUBLIC_BASE_URL=http://127.0.0.1:8080
DEVELOPMENT_MODE=true
SITE_TITLE=Adelia
SITE_SUBTITLE=Independent discussion for hobby and educational communities
SECURE_COOKIES=false
DB_MIN_CONNECTIONS=2
DB_MAX_CONNECTIONS=20
MAX_UPLOAD_BYTES=8388608
MAX_BODY_CHARS=20000
SESSION_HOURS=12
GENERATED_DIR=generated
UPLOAD_DIR=data/uploads
TEMPLATE_DIR=app_templates
ASSET_DIR=web/assets
RUST_LOG=adelia=info,tower_http=info
EOF

    cargo run -- rebuild
    echo "Local moderator login: admin / mod"
fi

exec cargo run -- serve
