$ErrorActionPreference = 'Stop'

function ConvertFrom-SecureValue([Security.SecureString]$Value) {
    $pointer = [Runtime.InteropServices.Marshal]::SecureStringToBSTR($Value)
    try {
        [Runtime.InteropServices.Marshal]::PtrToStringBSTR($pointer)
    }
    finally {
        [Runtime.InteropServices.Marshal]::ZeroFreeBSTR($pointer)
    }
}

function New-UrlToken([int]$ByteCount) {
    $bytes = New-Object byte[] $ByteCount
    $generator = [Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $generator.GetBytes($bytes)
    }
    finally {
        $generator.Dispose()
    }
    [Convert]::ToBase64String($bytes).Replace('+', '-').Replace('/', '_').TrimEnd('=')
}

$projectRoot = Split-Path -Parent $PSScriptRoot
Set-Location -LiteralPath $projectRoot

if (-not (Get-Command cargo -ErrorAction SilentlyContinue)) {
    throw 'Rust/Cargo was not found. Install Rust from https://rustup.rs/ and reopen the terminal.'
}

if (Test-Path -LiteralPath '.env') {
    Write-Host 'Existing .env found; keeping the current database credentials.'
    & cargo run -- rebuild
    if ($LASTEXITCODE -ne 0) { throw 'Adelia could not connect, migrate, and rebuild.' }
    exit 0
}

$postgresRoot = Get-ChildItem -LiteralPath 'C:\Program Files\PostgreSQL' -Directory -ErrorAction Stop |
    Where-Object { $_.Name -match '^\d+$' } |
    Sort-Object { [int]$_.Name } -Descending |
    Select-Object -First 1
if (-not $postgresRoot) { throw 'PostgreSQL was not found under C:\Program Files\PostgreSQL.' }

$postgresBin = Join-Path $postgresRoot.FullName 'bin'
$psql = Join-Path $postgresBin 'psql.exe'
$createdb = Join-Path $postgresBin 'createdb.exe'
if (-not (Test-Path -LiteralPath $psql) -or -not (Test-Path -LiteralPath $createdb)) {
    throw 'PostgreSQL command-line tools were not found.'
}

$databaseName = 'adelia_dev'
$roleName = 'adelia_app'
$databasePassword = New-UrlToken 36
$appSecret = New-UrlToken 48
$adminPassword = ConvertFrom-SecureValue (Read-Host 'PostgreSQL postgres password' -AsSecureString)
$env:PGPASSWORD = $adminPassword

try {
    & $psql -h localhost -U postgres -d postgres -v ON_ERROR_STOP=1 -Atc 'SELECT 1' | Out-Null
    if ($LASTEXITCODE -ne 0) { throw 'Could not connect to PostgreSQL as postgres.' }

    $roleExists = [string](& $psql -h localhost -U postgres -d postgres -Atc "SELECT 1 FROM pg_roles WHERE rolname='$roleName'")
    if ($roleExists.Trim() -eq '1') {
        $roleSql = "ALTER ROLE $roleName PASSWORD '$databasePassword';"
    }
    else {
        $roleSql = "CREATE ROLE $roleName LOGIN PASSWORD '$databasePassword';"
    }
    $roleSql | & $psql -h localhost -U postgres -d postgres -v ON_ERROR_STOP=1
    if ($LASTEXITCODE -ne 0) { throw 'Could not create or update the Adelia application role.' }

    $databaseExists = [string](& $psql -h localhost -U postgres -d postgres -Atc "SELECT 1 FROM pg_database WHERE datname='$databaseName'")
    if ($databaseExists.Trim() -ne '1') {
        & $createdb -h localhost -U postgres -O $roleName $databaseName
        if ($LASTEXITCODE -ne 0) { throw 'Could not create the Adelia development database.' }
    }
}
finally {
    Remove-Item Env:PGPASSWORD -ErrorAction SilentlyContinue
    $adminPassword = $null
}

$environment = @"
# Generated by scripts/setup-windows.ps1 for loopback-only development.
DATABASE_URL=postgres://$($roleName):$databasePassword@localhost:5432/$databaseName
APP_SECRET=$appSecret
BIND_ADDR=127.0.0.1:8080
PUBLIC_BASE_URL=http://127.0.0.1:8080
DEVELOPMENT_MODE=true
SITE_TITLE=Adelia
SITE_SUBTITLE=Independent discussion for hobby and educational communities
SECURE_COOKIES=false
DB_MIN_CONNECTIONS=2
DB_MAX_CONNECTIONS=20
MAX_UPLOAD_BYTES=8388608
MAX_BODY_CHARS=20000
SESSION_HOURS=12
GENERATED_DIR=generated
UPLOAD_DIR=data/uploads
TEMPLATE_DIR=app_templates
ASSET_DIR=web/assets
RUST_LOG=adelia=info,tower_http=info
"@
Set-Content -LiteralPath '.env' -Value $environment -Encoding UTF8
Write-Host 'Created .env with unique local database and application secrets.'

& cargo run -- rebuild
if ($LASTEXITCODE -ne 0) { throw 'Adelia could not migrate and build its initial pages.' }

Write-Host ''
Write-Host 'Adelia local development is ready.' -ForegroundColor Green
Write-Host 'Moderator login: admin / mod' -ForegroundColor Green
Write-Host 'Run dev.bat and open http://127.0.0.1:8080/' -ForegroundColor Green
